### ДЗ 2. NumPy

1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [1]:
import numpy as np

In [2]:
iris = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=str, delimiter=',') 
# iris = np.genfromtxt('./hw-2/iris-data.csv', delimiter=',', dtype=str) 
iris[:5]

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa']], dtype='<U15')

In [20]:
iris = iris[:, :-1].astype(float)
iris[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)


In [21]:
print(iris.ndim)

2


3. Порахувати mean, median, standard deviation для 1-ї колонки

In [23]:
mean = np.mean(iris[0], axis=0)
median = np.median(iris[0], axis=0)
stdev = np.std(iris[0], axis=0)
print(mean)
print(median)
print(stdev)

2.55
2.45
1.8874586088176872


4. Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)


In [27]:
random_row_indexes_to_replace = np.random.choice(iris.shape[0], size=20, replace=False)
for row_index in random_row_indexes_to_replace:
    col_index = np.random.randint(iris.shape[1])  
    iris[row_index, col_index] = np.nan

5. Знайти позиції вставлених значень np.nan в 1-й колонці

In [35]:
nan_indexes = np.where(np.isnan(iris[:, 0]))
print(nan_indexes)

(array([ 21,  53,  68,  71, 111, 121, 135, 142]),)


6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [ ]:
mask = (iris[:, 2] > 1.5) & (iris[:, 0] < 5.0)
# variant 1
# filtered_iris = iris[mask] 

# variant 2
filtered_iris_indexes = np.where(mask)
filtered_iris = iris[filtered_iris_indexes]

7. Замінити всі значення np.nan на 0

In [37]:
iris[np.isnan(iris)] = 0

8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

In [48]:
unique_values, counts = np.unique(iris, return_counts=True)
# variant 1
# u_values_and_counts = np.row_stack((unique_values, counts))
# variant 2
u_values_and_counts = np.vstack([unique_values, counts])
u_values_and_counts

array([[ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  1. ,  1.1,  1.2,  1.3,
         1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,
         2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,
         3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,
         4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,
         5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,
         6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.6,  7.7,  7.9],
       [20. ,  6. , 26. ,  7. ,  7. ,  1. ,  1. ,  8. ,  4. ,  7. , 19. ,
        20. , 25. , 11. ,  6. , 12. ,  7. ,  7. ,  5. ,  6. , 12. ,  6. ,
        11. ,  5. ,  9. , 14. , 10. , 26. , 11. , 13. ,  8. , 12. ,  8. ,
         4. ,  4. ,  7. ,  5. ,  6. ,  4. ,  5. ,  2. ,  8. ,  8. ,  7. ,
         6. ,  9. , 11. , 14. , 16. ,  6. ,  3. ,  8. ,  8. , 11. , 10. ,
         9. ,  5. ,  8. ,  8. ,  3. , 10. ,  7. ,  5. ,  3. , 10. ,  3. ,
         5. ,  1. ,  1. ,  3. ,  1. ,  1. ,  1. ,

9. Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [53]:
iris_part1, iris_part2 = np.vsplit(iris, 2)
print(iris_part1.shape)
print(iris_part2.shape)

(75, 4)
(75, 4)


10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [55]:
iris_part1[iris_part1[:, 0].argsort()]

array([[0. , 3.7, 1.5, 0.4],
       [0. , 2.8, 4. , 1.3],
       [0. , 2.3, 4. , 1.3],
       [0. , 2.2, 4.5, 1.5],
       [4.3, 3. , 1.1, 0.1],
       [4.4, 3. , 1.3, 0. ],
       [4.4, 3.2, 1.3, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.6, 3.1, 1.5, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3.1, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 0. , 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 2.4, 3.3, 1. ],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.5, 1.6, 0.6],
       [5. , 3.2, 1.2, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5. , 2. , 3.5, 1. ],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.1, 3

In [56]:
iris_part2[iris_part2[:, 0].argsort()[::-1]]

array([[7.9, 3.8, 6.4, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [7.7, 2.6, 6.9, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [7.4, 2.8, 6.1, 1.9],
       [7.3, 2.9, 6.3, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [7.2, 0. , 5.8, 1.6],
       [7.2, 3.2, 6. , 1.8],
       [7.1, 3. , 5.9, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.9, 3.1, 5.4, 2.1],
       [6.8, 3. , 5.5, 2.1],
       [6.8, 3.2, 5.9, 2.3],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 2.5, 5.8, 1.8],
       [6.7, 3.1, 5.6, 2.4],
       [6.7, 3.1, 4.7, 1.5],
       [6.7, 3.3, 0. , 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 3. , 5. , 1.7],
       [6.7, 3.3, 5.7, 0. ],
       [6.6, 3. , 4.4, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6.5, 3. , 5.5, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.8, 5.6, 2.1],
       [6.4, 2.8, 5.6, 2.2],
       [6.4, 3.2, 5.3, 2.3],
       [6.4, 3.1, 0. , 1.8],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 3

11. Зібрати обидва массиви в одне ціле

In [60]:
merged_iris = np.row_stack((iris_part1, iris_part2))
merged_iris.shape

(150, 4)

12. Знайти найбільш часто повторюване значення в массиві

In [61]:
iris_values, iris_counts = np.unique(iris, return_counts=True)
max_count_index = np.argmax(iris_counts)
iris_values[max_count_index]

0.2

13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [67]:
def multiply_or_divide(column):
    def transform(val, avg):
        if val > avg:
            return val * 2
        else:
            return val / 4

    vfunc = np.vectorize(transform)

    return vfunc(column, column.mean())

14. Застосувати отриману функцію до 3-ї колонки

In [73]:
updated_col = multiply_or_divide(iris[:, 2])
updated_col

array([ 0.35 ,  0.35 ,  0.325,  0.375,  0.35 ,  0.425,  0.35 ,  0.375,
        0.35 ,  0.375,  0.375,  0.4  ,  0.35 ,  0.275,  0.3  ,  0.375,
        0.325,  0.35 ,  0.425,  0.375,  0.425,  0.375,  0.25 ,  0.425,
        0.475,  0.4  ,  0.4  ,  0.375,  0.35 ,  0.4  ,  0.4  ,  0.375,
        0.375,  0.35 ,  0.375,  0.3  ,  0.325,  0.375,  0.325,  0.375,
        0.325,  0.325,  0.325,  0.4  ,  0.475,  0.35 ,  0.4  ,  0.35 ,
        0.375,  0.35 ,  9.4  ,  9.   ,  9.8  ,  8.   ,  9.2  ,  0.   ,
        9.4  ,  0.825,  9.2  ,  7.8  ,  0.875,  8.4  ,  8.   ,  0.   ,
        7.2  ,  8.8  ,  9.   ,  8.2  ,  9.   ,  7.8  ,  9.6  ,  8.   ,
        9.8  ,  9.4  ,  8.6  ,  8.8  ,  9.6  , 10.   ,  9.   ,  0.875,
        7.6  ,  7.4  ,  7.8  , 10.2  ,  9.   ,  9.   ,  9.4  ,  8.8  ,
        8.2  ,  8.   ,  8.8  ,  9.2  ,  8.   ,  0.825,  8.4  ,  8.4  ,
        8.4  ,  0.   ,  0.75 ,  8.2  , 12.   , 10.2  , 11.8  , 11.2  ,
       11.6  , 13.2  ,  9.   , 12.6  , 11.6  , 12.2  , 10.2  , 10.6  ,
      

In [74]:
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 0. , 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [0. , 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3